{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server.fullname" . }}-secrets
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
